#spring:
logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
#    '[org.mongodb.driver]': warn
    '[ai.mlhub.platform.feast.client.FeastServingFeignClient]': debug
debug: false

server:
  port: 8090
  forward-headers-strategy: framework
#  servlet:
#      context-path:

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

#------------------------- Spark configurations -------------------------
spark:
  master: local
  app.name: ${spring.application.name}
  local.dir: spark-space/tmp
  driver:
    memory: 4g
    cores: 4
  executor:
    instances: 4
    memory: 2g
    cores: 2
  ui:
    enabled: false
  default:
    parallelism: 32
  sql:
    datetime.java8API.enabled: true
    session.timeZone: "+05:30"
    #    extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    #    - org.projectnessie.spark.extensions.NessieSparkSessionExtensions
    #    extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
#    defaultCatalog: nessie
    #    Catalog name is local, can be set to any value
    catalog:
      nessie: org.apache.iceberg.spark.SparkCatalog
      nessie.type: nessie
      nessie.warehouse: s3a://iceberg-bucket
      nessie.uri: http://localhost:19120/api/v1
      nessie.default-namespace: ksoot
      #      nessie.ref: "main"
      nessie.io-impl: org.apache.iceberg.aws.s3.S3FileIO
  hadoop:
    fs:
      s3a:
        aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
        access.key: ${AWS_ACCESS_KEY:}
        secret.key: ${AWS_SECRET_KEY:}
        endpoint: ${AWS_S3_ENDPOINT:s3.ap-south-1.amazonaws.com}
        impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        path.style.access: true  # For path-style access, useful in some S3-compatible services
        connection.ssl.enabled: false  # Enable SSL
        fast.upload: true  # Enable faster uploads