#spring:
logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
#    '[org.mongodb.driver]': warn
debug: false

server:
  port: 8090
  forward-headers-strategy: framework
#  servlet:
#      context-path:

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

#------------------------- Spark configurations -------------------------
spark:
  master: local
  app.name: ${spring.application.name}
  local.dir: spark-space/tmp
  driver:
    memory: 4g
    cores: 4
  executor:
    instances: 4
    memory: 2g
    cores: 2
  ui:
    enabled: false
  default:
    parallelism: 32
  sql:
    datetime.java8API.enabled: true
    session.timeZone: "+05:30"
    #    extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    #    - org.projectnessie.spark.extensions.NessieSparkSessionExtensions
    #    extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
#    defaultCatalog: hadoop
    #    Catalog name is local, can be set to any value
    catalog:
      hive: org.apache.iceberg.spark.SparkCatalog
      hive.type: hive
      hive.uri: thrift://localhost:9083
      hive.warehouse: /user/hive/warehouse
      hive.default-namespace: ksoot
