# spark atlas configuration ::

spark.atlas.rest.address=http://localhost:21000/
spark.atlas.cluster.name=primary
spark.atlas.metadata.namespace=spark

# atlas connectivity configuration ::
atlas.enableTLS=false
atlas.debug.properties=true
atlas.rest.address=http://localhost:21000/
atlas.cluster.name=primary
atlas.authentication.method.basic=true
atlas.authentication.username=admin
atlas.authentication.password=atlasR0cks!

# atlas lineage configuration ::
atlas.hook.spark.column.lineage.enable=true

# atlas kafka configuration ::

atlas.kafka.bootstrap.servers=localhost:9092
#atlas.kafka.zookeeper.connect=localhost:2181
atlas.kafka.auto.commit.interval.ms=1000
atlas.kafka.group.id=atlas
atlas.kafka.session.timeout.ms=30000


